name: human-detection-cuda
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy>=1.16
  - pytorch>0.4
  - pip
  - jupyterlab
  - visdom
  - scikit-learn
  - cudatoolkit=10.1
  - pip:
    - torchvision==0.1.9
    - opencv-python
    - matplotlib
