name: human-detection
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy>=1.16
  - pytorch>0.4
  - pip
<<<<<<< HEAD:environment.yaml
=======
  - jupyterlab
>>>>>>> master:environment.yml
  - pip:
    - torchvision==0.1.9
    - opencv-python
